### PR TITLE
Fix so it compiles with UIKit classes

### PR DESCRIPTION
**Pull request by CocoaPriest**
Needed for classes like UIColor and CGFloat

### CODE REVIEW

**Comment by Sam-Spencer** [comment]
Does this properly compile without importing Foundation?

**Comment by CocoaPriest** [comment]
it doesn't. UIColor is an UIKit class, not Foundation

**Comment by Sam-Spencer** [comment]
I'm not sure I understand then. This class should need both UIKit and Foundation imported:

    @import UIKit; 
    @import Foundation;

**Comment by CocoaPriest** [comment]
UIKit.h doesn't explicitly include Foundation, but one of the other UIKit headers does, AFAIK.

**Comment by Sam-Spencer** [comment]
Thanks for the pull request (and congrats on being number 200 :fireworks:)!!

**Comment by CocoaPriest** [comment]
ha, I didn't notice that

**Pull request merged**
