### PR TITLE
Added a bunch of options including left/right y axis positioning, float values in Y-Axis and popovers, null graph values, and customizations around how the X and Y axes are displayed!

### PR DESCRIPTION
**Pull request by RobDay**
Hey All,

This is a continuation of the pull request here: https://github.com/Boris-Em/BEMSimpleLineGraph/pull/129. I have since closed that PR as more work has been done from our end.  Things added since that pull request's creation:

 - Customization of how we draw axes labels.  
     - X-Axis: these changes give you two strategies to set a starting index for the X-Axis labels and then an increment to repeat the labels.  It also exposes a way to simply return an array of indices that should be used to draw the labels.  Consider a use case where you're plotting minute data.  If you want all of your X-Axis labels to only be displayed square on the hour, you could use these new methods.
     - Y-Axis: these changes allow you to set a base float value & an increment to draw Y-Axis labels.  This gives fine tuning to the granularity of the data displayed on the Y-Axis.

We're also changed how the pan gesture recognizer works so that we can get alerted when the user simply touches the chart rather than when they start dragging.

Considering the wiki is readonly, do you have a strategy for taking my edits to it?

### CODE REVIEW

**Comment by Sam-Spencer** [comment]
@RobDay Thanks again for all the fantastic work on this! As for the wiki, rather than trying to directly edit it maybe you could create a `New Release Details.md` file. The file would be in markdown and describe the new / changed features in your PR. We could then transfer parts to either the wiki or `README.md` appropriately. Does this sound like a reasonable solution?

**Comment by RobDay** [comment]
Works for me. I'll write it up tomorrow.

**Comment by RobDay** [comment]
Hey @Sam-Spencer, here is the body of my changes.  If you want me to send the file somewhere, let me know and I'll do so.


### New features with pull request #130:

`positionYAxisRight`- Boolean flag that moves the Y-Axis to the right of the graph
`lineDashPatternForReferenceX[A|Y]xisLines`- Specify a dash pattern for the reference lines drawn on the graph.  This creates the reference lines with a dotted or hashed pattern.
`enable[Left|Right|Top|Bottom]ReferenceAxisFrameLine`- By setting these properties, you can control what reference frame lines are drawn on the graph
`displayDotsWhileAnimating`- Boolean specifying whether or not to show the dots while animating the reference lines
`noDataLabelColor`- Specify the color for the no data label
`noDataLabelFont`- Specify the font for the no data label
`formatStringForValues`- A format string to apply to values in the Y-Axis.  This lets you have fine-grain control over the decimal precision of these values (eg. ".02f")
`yAxis[Prefix|Suffix]OnLineGraph`- Specify popup prefix and suffix to show in the built-in popup view


#### Null graph values

The graph now has the ability to plot null graph values.  `BEMSimpleLineGraph.h` now specifies a special value, `BEMNullGraphValue`, that corresponds to a null data point.  In your response to `valueForPointAtIndex`, return this special value whenever your data point is null.  BEMSimpleLineGraph will now skip over this value when drawing the line. If you set `interpolateNullValues`, the graph will connect non-null values while preserving spacing for the null value.


#### Customizing popup view

`popUpSuffixForlineGraph:`- A suffix to append to the stock pop up label view's value
`popUpPrefixForlineGraph:`- A prefix to prepend to the stock pop up label view's value

If you want to use a custom popup view instead of the built-in popup view, you can respond to the optional method `popUpViewForLineGraph:`. You respond to this method with a UIView that will be used in place of the default popup.  

When you use the custom popup view, the data in the view needs to be changed whenever the user drags his or her finger.  To handle this modification, BEMSimpleLineGraph will send the message `lineGraph:modifyPopupView:ForIndex:`.  This lets you modify your view for a given datapoint. 


#### Axis customizations
These customizations took some influence from the strategy Highcharts uses to customize their axis labels.  There are two ways to customize the positioning of X-Axis labels on the graph:

`incrementPositionsForXAxisOnLineGraph`- A delegate method that lets you set the specific indices where X-Axis labels should be drawn


`baseIndexForXAxisOnLineGraph`- The index of the first X-Axis label to draw

AND

`incrementIndexForXAxisOnLineGraph`- An increment to apply to the response to `baseIndexForXAxisOnLineGraph`.  X-Axis labels will be drawn on this increment across the X-Axis


There is one way to customize the Y-Axis:
`baseValueForYAxisOnLineGraph`- The starting Y-Axis value to plot draw on the Y-Axis.  This lets you set a specifically formatted value so that your access label can be more user friendly (21.50 instead of 21.47)

`incrementValueForYAxisOnLineGraph`- An increment value to add to the response of `baseValueForYAxisOnLineGraph` that specifies what Y-Axis values to draw.  This lets you return a user friendly increment, eg. .25.

**Comment by Sam-Spencer** [comment]
I've looked over everything and it seems great! I did notice that the popup views seemed to almost waver as the user drags along the graph. I'm not sure what the reason for this is -- maybe you can figure it out and let us know about a fix. 

After I resolve some of the conflicts, your PR will be merged. Thank you so much for these contributions!

**Pull request merged**
