### PR TITLE
update changelog

### PR DESCRIPTION
**Pull request by skywinder**
update changelog by  github_changelog_generator

### CODE REVIEW

**Comment by Sam-Spencer** [comment]
Please provide more details about this Pull Request. Until that time, this request is being closed.

**Comment by skywinder** [comment]
@Sam-Spencer the [changelog](https://github.com/Boris-Em/BEMSimpleLineGraph/blob/master/CHANGELOG.md) in this repo generated by  [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator), that generate change log file based on tags, issues and merged pull requests (and split them to separate lists according labels) from GitHub issue tracker.

I just this PR is simply update this change log. (however, not Unreleased section should be named `v3.3`

**Comment by Sam-Spencer** [comment]
Thanks for the pull request! I just installed your awesome software and updated the Changelog on the repo to the latest changes. Thanks for this great tool! I hope to see integration with the GitHub site in the future (as Travis CI and other apps do).

**Comment by skywinder** [comment]
@Sam-Spencer Thanks, very glad to hear it! :tada: 
Hope, I can pay attention of GitHub team in the future, since it's work nice with all well-tagged-and-labeled repos. :books:

**Comment by Sam-Spencer** [comment]
I took a look into it, and with a little work using [GitHub's Service API](https://developer.github.com/webhooks/#service-hooks) you may be able to get your tool added to their Repository *Services* list quite easily. Best of luck!

**Pull request closed without merging**
